### ISSUE TITLE
Intro ToDo

### ISSUE THREAD

**Issue by story645** [story645/second_exam#1]
- [x] semiology
- [ ] Visualization Zoo [heer2010.pdf](https://github.com/story645/second_exam/files/1220292/heer2010.pdf)
- [ ] Grammer of Graphics [wilkinson2005.pdf](https://github.com/story645/second_exam/files/1220291/wilkinson2005.pdf)
- [x] Munzner
- [ ] Probalistic Models - Daphne Kolner
- [ ] Functional Data Analysis
